# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MachineLearning_ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'TensorFlow-experimental'
  # Pods for MachineLearning_ios

  target 'MachineLearning_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MachineLearning_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
